# Generated by Django 2.2.6 on 2019-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animaltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typen', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='typen',
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(max_length=30),
        ),
    ]
