# Generated by Django 2.2.6 on 2019-10-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191022_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='typen',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=30),
        ),
    ]
