# Generated by Django 2.2.6 on 2019-11-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191022_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltype',
            name='typen',
        ),
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='animaltype',
            name='type',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=30),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
