# Generated by Django 2.2.6 on 2020-02-12 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200212_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.AnimalType'),
        ),
    ]
